### ISSUE TITLE
Hexo提高加载速度

### ISSUE THREAD

**Issue by CloudyCity** [CloudyCity/CloudyCity.github.io#26]
---
cover: https://guanqr.com/images/speed-up-hexo.png
---
Hexo作为纯静态博客最大的优点就是快，但要真正的快起来你可能需要做这些事情。

## 托管平台（可选）
直接在[Coding](https://coding.net/)等国内平台托管`Page`项目，修改国内线路解析。(可参照[Github Hexo的百度收录问题](https://cloudycity.me/p/c283.html#%E5%88%86%E7%BA%BF%E8%B7%AF%E8%A7%A3%E6%9E%90))
Coding绑定了域名需定期申请SSL证书，所以本博放弃此项。

## CDN加速
这里只是针对第三方静态文件的加速，修改`Next`主题配置文件`_config.yml`如下：

:::details Click to see more

```
vendors:
  # Internal path prefix. Please do not edit it.
  _internal: lib

  # Internal version: 2.1.3
  jquery: https://cdn.bootcss.com/jquery/2.1.3/jquery.min.js

  # Internal version: 2.1.5
  # See: http://fancyapps.com/fancybox/
  fancybox: https://cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.js # https://cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.pack.js
  fancybox_css: https://cdn.bootcss.com/fancybox/2.1.5/jquery.fancybox.min.css

  # Internal version: 1.0.6
  # See: https://github.com/ftlabs/fastclick
  fastclick: https://cdn.bootcss.com/fastclick/1.0.6/fastclick.min.js

  # Internal version: 1.9.7
  # See: https://github.com/tuupola/jquery_lazyload
  lazyload: https://cdn.bootcss.com/jquery_lazyload/1.9.7/jquery.lazyload.min.js

  # Internal version: 1.2.1
  # See: http://VelocityJS.org
  velocity: https://cdn.bootcss.com/velocity/1.2.1/velocity.min.js

  # Internal version: 1.2.1
  # See: http://VelocityJS.org
  velocity_ui: https://cdn.bootcss.com/velocity/1.2.1/velocity.ui.min.js

  # Internal version: 0.7.9
  # See: https://faisalman.github.io/ua-parser-js/
  ua_parser:

  # Internal version: 4.6.2
  # See: http://fontawesome.io/
  fontawesome: https://cdn.bootcss.com/font-awesome/4.6.2/css/font-awesome.min.css

  # Internal version: 1
  # https://www.algolia.com
  algolia_instant_js:
  algolia_instant_css:

  # Internal version: 1.0.2
  # See: https://github.com/HubSpot/pace
  # Or use direct links below:
  # pace: //cdn.bootcss.com/pace/1.0.2/pace.min.js
  # pace_css: //cdn.bootcss.com/pace/1.0.2/themes/blue/pace-theme-flash.min.css
  pace: https://cdn.bootcss.com/pace/1.0.2/pace.min.js
  pace_css: https://cdn.bootcss.com/pace/1.0.2/themes/blue/pace-theme-flash.min.css
```

:::

:::warning
针对自定义的静态文件(main.min.js和main.min.css)需要自行使用融合CDN，国内都需要备案域名，本博的`.me`域名没有备案资质，但我不太想将静态文件放到其他域名，所以放弃加速这类文件。
:::

#### 安装
```bash
npm install hexo-neat --save
```

#### 配置
修改项目`_config.yml`。

```
neat_enable: true
neat_html:
  enable: true
  exclude:
neat_css:
  enable: false
  exclude:
    - '**/*.min.css'
neat_js:
  enable: false
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
```

:::tip后面会使用`gulp`合并与压缩js与css，所以此处只用`neat`压缩了html。如果你不想使用合并js与css，此处可以打开`neat_js`、`neat_css`。
:::

### gulp
`gulp`是自动化构建工具，这里主要是用来合并、压缩js与css。

#### 构建配置
`Next`主题目录自带了`gulpfile.coffee`，这里直接修改：

:::details Click to see more

```
fs = require('fs')
path = require('path')
gulp = require('gulp')
jshint = require('gulp-jshint') # js语法检查
jslish = require('jshint-stylish') # js语法检查输出美化
stylint = require('gulp-stylint') # stylus语法检查
stylish = require('stylint-stylish') # stylus语法检查输出美化
yaml = require('js-yaml')
concat = require('gulp-concat') # js合并
uglify = require("gulp-uglify") # js压缩
concatCss = require('gulp-concat-css') # css合并
cleanCss = require('gulp-clean-css') # css压缩

# js语法检查 https://jshint.com/docs/options/
gulp.task 'lint:js', ->
  return gulp.src path.join(__dirname, './source/js/**/*.js')
    .pipe jshint()
    .pipe jshint.reporter()

# stylus语法检查 https://github.com/SimenB/stylint
gulp.task 'lint:stylus', ->
  return gulp.src path.join(__dirname, '/source/css/**/*.styl')
    .pipe stylint({config: path.join(__dirname, '.stylintrc')})
    .pipe stylint.reporter(stylish)

# 配置文件检验
gulp.task 'validate:config', (cb) ->
  themeConfig = fs.readFileSync path.join(__dirname, '_config.yml')
  try
    yaml.safeLoad(themeConfig)
    cb()
  catch error
    cb new Error(error)

# 语言文件检验
gulp.task 'validate:languages', (cb) ->
  languagesPath = path.join __dirname, 'languages'
  languages = fs.readdirSync languagesPath
  errors = []

  for lang in languages
    languagePath = path.join languagesPath, lang
    try
      yaml.safeLoad fs.readFileSync(languagePath), {
        filename: path.relative(__dirname, languagePath)
      }
    catch error
      errors.push error

  if errors.length == 0
    cb()
  else
    cb(errors)

# 合并压缩js
# gulp.task 'minify:js', ['lint:js'], (cb) ->
gulp.task 'minify:js', (cb) ->
  return gulp.src([
    path.join(__dirname, 'source/js/src/utils.js'),
    path.join(__dirname, 'source/js/src/motion.js'),
    path.join(__dirname, 'source/js/src/gitment.browser.js'),
    path.join(__dirname, 'source/js/src/bootstrap.js'),
    path.join(__dirname, 'source/js/src/scrollspy.js'),
    path.join(__dirname, 'source/js/src/post-details.js'),
  ]).pipe concat('main.min.js')
    .pipe uglify()
    .pipe gulp.dest path.join __dirname, '../../public/js'

# 合并压缩js
# gulp.task 'minify:css', ['lint:stylus'], (cb) ->
gulp.task 'minify:css', (cb) ->
  return gulp.src([
    path.join(__dirname, '../../public/css/main.css'),
    path.join(__dirname, 'source/css/src/gitment.css'),
  ]).pipe concat('main.min.css')
    .pipe cleanCss()
    .pipe gulp.dest path.join __dirname, '../../public/css'

# 执行
gulp.task 'default', [
  'validate:config',
  'validate:languages'
  'minify:js',
  'minify:css',
]
```

:::

:::tip
`Next`主题默认的`gulpfile.coffee`只是进行规范检查，不过此处修改后默认关闭，按需开启。
:::

:::warning
合并js时尽量保持模板中引入的顺序，避免不必要错误。
:::

在项目根目录下新建`gulpfile.js`：
```
require('coffeescript/register')
require('./themes/next/gulpfile.coffee')
```
#### 安装相关依赖
安装构建任务用到的依赖。
```
npm install gulp -g
npm install coffeescript --save-dev # 用于在gulpfile.js中引入gulpfile.coffee
npm install gulp-clean-css --save-dev # css压缩
npm install gulp-concat --save-dev # js合并
npm install gulp-concat-css --save-dev # css合并
npm install gulp-jshint --save-dev # js语法检查
npm install gulp-stylint --save-dev # css语法检查
npm install gulp-uglify --save-dev # js压缩
npm install jshint --save-dev # js压缩核心
npm install jshint-stylish --save-dev # js语法检查输出美化
npm install stylint-stylish --save-dev # css语法检查输出美化
```
#### 执行构建
项目根目录执行`gulp`：

![image](https://user-images.githubusercontent.com/17662451/57032007-d1507900-6c7b-11e9-8c4f-22be1b05c910.png)

构建输出合并与压缩后的文件：

![image](https://user-images.githubusercontent.com/17662451/57032110-23919a00-6c7c-11e9-8999-a24577e5296e.png)

#### 更新模板
修改`themes/next/layout/_partials/head.swig`:
```
<link href="{{ font_awesome_uri }}" rel="stylesheet" type="text/css" />


 <link href="{{ url_for(theme.css) }}/main.css?v={{ theme.version }}" rel="stylesheet" type="text/css" />	<link href="{{ url_for(theme.css) }}/main.min.css?v={{ theme.version }}" rel="stylesheet" type="text/css" />


 {% if theme.favicon.apple_touch_icon %}	{% if theme.favicon.apple_touch_icon %}
```

修改`themes/next/layout/_layout.swig`:
```
{% include '_scripts/vendors.swig' %}
  <script type="text/javascript" src="{{ url_for(theme.js) }}/main.min.js?v={{ theme.version }}"></script>
  {% include '_scripts/commons.swig' %}	  {% include '_scripts/commons.swig' %}
```

然后在各模板中将引入合并前静态文件的部分注释掉，这里不详细列出，只放出一个例子：

![image](https://user-images.githubusercontent.com/17662451/57033148-b92e2900-6c7e-11e9-88f9-c86d8bd93e11.png)

完成后重新部署：
```
hexo g && gulp && hexo d
```

引用效果：

![image](https://user-images.githubusercontent.com/17662451/57033361-52f5d600-6c7f-11e9-8857-167b5a80eccf.png)

## 图片懒加载
可以显著加速文章页。

安装插件:
```
npm install hexo-lazyload-image --save
```

修改项目配置文件`_config.yml`:
```
# 图片懒加载
lazyload:
  enable: true 
  onlypost: false
  loadingImg: /images/loading/loading.gif #如果不填写图片则使用默认的图片
```

## 精简功能
功能涉及多个请求时会比较明显得拖慢加载速度，例如`不蒜子`、`DaoVice`，要考量这些功能是否真(hua)的(er)需(bu)要(shi)。（像我已经关掉了`DaoVice`，只留着`不蒜子`计算站点UV）

## 最终效果
首页

![image](https://user-images.githubusercontent.com/17662451/57033434-7caefd00-6c7f-11e9-9b23-fb7f0b8b4d5d.png)

文章页

![image](https://user-images.githubusercontent.com/17662451/57034951-6f940d00-6c83-11e9-8ae7-836267fff2b4.png)

剩下的瓶颈主要是`Gitment`、`不蒜子`。

:::tip
不同网络环境下的加速效果也会不同，以上效果是我在家中的加速效果。在公司的加速效果就差了很多。
:::
